# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-07 10:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0001_initial'),
        ('todo', '0003_todo_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='tags',
            field=models.ManyToManyField(to='tags.Tag'),
        ),
    ]
